### ISSUE TITLE
Completion only functioning on attributes

### ISSUE THREAD

**Issue by itepastra** [ThePrimeagen/htmx-lsp#11]
When I have an html file like
```
<div hx
</div>
```
and a `-` is added the lsp does not display any autocompletions.
![image](https://github.com/ThePrimeagen/htmx-lsp/assets/27058689/bb081bea-b2fb-46f0-bf48-d0208e67e349)

For the attributes like
```
<div hx-swap="
</div>
```
it does work as expected and shows the possible completions
![image](https://github.com/ThePrimeagen/htmx-lsp/assets/27058689/04d38e72-18c7-4221-88d8-1d02239698b7)

I included the log of me starting the lsp and adding a `-` to the line
[lsp.log](https://github.com/ThePrimeagen/htmx-lsp/files/12445348/lsp.log)

**Comment by cristianoliveira** [comment]
@itepastra 

I think this PR #12 solves that issue :D 

I hope it won't cause a giant merge conflict with yours #9 😅

**Comment by itepastra** [comment]
It shouldn't cause a merge conflict, the test might break however since I did add an extra tag
`hx-ext` for extensions which is not included in the test, so that should be looked into when both get merged and the test breaks.

**Comment by ThePrimeagen** [comment]
I just pushed up a change recently.

It may have broken this. I think it's time to start investing in some good testing.

**Comment by itepastra** [comment]
I think #13 solves this issue and also includes some testing so the issue doesn't reappear

**Comment by itepastra** [comment]
#13 did indeed solve this issue, so I'm closing the issue.
