### ISSUE TITLE
Mason

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/htmx-lsp#24]
We now have `cargo install htmx-lsp` now we just need mason linking.

as of now, i am not able to do much until Nov 17th+, so i will not be looking much at this until then

**Comment by OZoneGuy** [comment]
Created PR: https://github.com/mason-org/mason-registry/pull/3084

**Comment by OZoneGuy** [comment]
PR has been merged! I think we should close the issue. Mason now gets the binary from Cargo, which I think is pushed via gh actions?

**Comment by MNThomson** [comment]
Unfortunately GH Actions aren't pushing to crates.io yet, @ThePrimeagen has been manually. I'd like to get that setup but it requires a GH Actions secret for Primes crates.io account

**Comment by OZoneGuy** [comment]
If we want to the latest binary to ship to Mason, we would need to update it to use the GitHub releases. Not an issue, but would need another PR to Mason. Let me know how you want to proceeed.

**Comment by MNThomson** [comment]
I'd like to get CI pushing to crates.io, but let's wait to hear from Prime on that. I don't think it matters for the next month since the v0.1.0 release is mostly fully featured (if i recall correctly) and changes since then haven't been major.

**Comment by maiksch** [comment]
I tried installing the lsp with Mason but got a bunch of `use of unstable library feature 'once_cell'` errors.

This is the install log:
```
Installing crate htmx-lsp@0.1.0…
    Updating crates.io index
  Installing htmx-lsp v0.1.0

... bunch of compiling here ...

  Compiling htmx-lsp-server v0.1.0
        error[E0658]: use of unstable library feature 'once_cell'
         --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/htmx-lsp-server-0.1.0/src/htmx/mod.rs:4:48
          |
        4 | use std::{collections::HashMap, path::PathBuf, sync::OnceLock};
          |                                                ^^^^^^^^^^^^^^
          |
          = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
```

Is this a problem on my end or is this something that needs to be fixed here?

**Comment by OZoneGuy** [comment]
What version of rust/cargo are you using?

You could be using an older/newer version that marks those as unstable.

**Comment by cabbage-cart** [comment]
> > What version of rust/cargo are you using? You could be using an older/newer version that marks those as unstable.
> 
> Well, that fixed my problem already. I haven't used Rust in a while and the versions where over a year old apparently.
> 
> rustup 1.25.1 (bb60b1e89 2022-07-12) rustc 1.65.0 (897e37553 2022-11-02) cargo 1.65.0 (4bc8f24d3 2022-10-20)
> 
> I updated them to the newest versions and now the htmx lsp installed without a problem 👍

Fixed my issue as well.
