### ISSUE TITLE
Django template support?

### ISSUE THREAD

**Issue by oieeaaaa** [ThePrimeagen/htmx-lsp#40]
Heysir...

This doesn't seem to be compatible with django templates o.O

<img width="1440" alt="Screenshot 2024-01-21 at 10 45 34 AM" src="https://github.com/ThePrimeagen/htmx-lsp/assets/37941956/41e72aa4-3aca-46a4-bf21-cae3c90b1efb">

However, it works fine if it's "pure" html? Maybe the django tags are messing it up __perchance__ 
<img width="1440" alt="Screenshot 2024-01-21 at 10 48 13 AM" src="https://github.com/ThePrimeagen/htmx-lsp/assets/37941956/0c0e9b51-e1cf-4564-811d-b6124b529cf7">

**Comment by oieeaaaa** [comment]
> You need to add something like this in your configuration:
> 
> ```lua
> htmx = function ()
>     local opts = {
>         filetypes = { "html", "htmldjango" }
>     }
>     require("lspconfig").htmx.setup(opts)
> end
> ```

That didn't work for me... :/

**Comment by DanielAndreasen** [comment]
Maybe share how your config looks like, where you setup your LSP

**Comment by ThePrimeagen** [comment]
this is a vim specific issue.  please review the documentation to see how to make LSPs trigger for specific file types.
