### ISSUE TITLE
SkillIssue:: installation with Mason

### ISSUE THREAD

**Issue by RafaelZasas** [ThePrimeagen/htmx-lsp#44]
I am trying to install with Mason, but get this error:
```   
 ◍ htmx-lsp
      ▼ Displaying full log
        Installing crate htmx-lsp@0.1.0…
        spawn: cargo failed with exit code - and signal -. cargo is not executable
```

I have rust and cargo installed:
```bash
cargo --version
cargo 1.76.0 (c84b36747 2024-01-18)
```

What am I doing wrong?

**Comment by ThePrimeagen** [comment]
this ... i have no idea.

i don't use mason but that is difficult to understand other than it says cargo is not an executable which is... well that doesn't make any sense

**Comment by ThePrimeagen** [comment]
i am closing it.  please review more of mason's documentation and ensure you have done it right.  i have had many people already respond with mason being successful

**Comment by AlperShal** [comment]
Had this exact problem just now. Installed rust/cargo on my system and that fixed.
