### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by RafaelZasas** [ThePrimeagen/htmx-lsp#46]
I have come to love the [response-targets](https://htmx.org/extensions/response-targets/) extension which allows you to specify `hx-target-401="#unauth"` or `hx-target-errors="#errDiv"`.

I know that there is support for the `hx-ext="<>"` attribute, but is there any plan to introduce suggestions based on an ext present in the document, or maybe a way to configure which extensions you use often, and would like suggestions for?

**Comment by MNThomson** [comment]
Related: "intelligent" support for `hx-ext` tags are being discussed in #14

**Comment by MNThomson** [comment]
Closing as implementation of #14 is preferred
